# Generated by Django 5.2 on 2025-04-03 04:15

import accounts_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="Required. Enter the user's first name (100 characters max).", max_length=100, validators=[django.core.validators.MinLengthValidator(2), accounts_app.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="Required. Enter the user's last name (100 characters max).", max_length=100, validators=[django.core.validators.MinLengthValidator(2), accounts_app.validators.validate_name], verbose_name='last name'),
        ),
    ]
