# Generated by Django 5.2 on 2025-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Admin Site Access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a staff member and has staff privileges within the application (Does NOT grant Admin portal access).', verbose_name='Staff Member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', help_text='Categorizes the user role within the application (Client, Staff, Admin).', max_length=10, verbose_name='User Type'),
        ),
    ]
